In [1]:
%pip install nba_api

Collecting nba_api
  Downloading nba_api-1.2.1-py3-none-any.whl (257 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 257.3/257.3 kB 3.6 MB/s eta 0:00:0000:01
Requirement already satisfied: numpy<2.0.0,>=1.22.2 in /Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages (from nba_api) (1.23.5)
Requirement already satisfied: requests in /Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages (from nba_api) (2.28.2)
Requirement already satisfied: charset-normalizer<4,>=2 in /Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages (from requests->nba_api) (3.0.1)
Requirement already satisfied: idna<4,>=2.5 in /Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages (from requests->nba_api) (3.4)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in /Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages (from requests->nba_api) (1.26.14)
Requirement already satisfied: certifi>=2017.4.17 in /Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages (from requests->nba_api) (2022.12.7)
Installing collected packages: nba_api
Successfully installed nba_api-1.2.1
Note: you may need to restart the kernel to use updated packages.

In [2]:
from nba_api.stats.endpoints import leaguegamefinder

In [15]:
gamefinder = leaguegamefinder.LeagueGameFinder(date_to_nullable='06/01/2023', league_id_nullable='00')
games = gamefinder.get_data_frames()[0]
games.head()

,SEASON_ID,TEAM_ID,TEAM_ABBREVIATION,TEAM_NAME,GAME_ID,GAME_DATE,MATCHUP,WL,MIN,PTS,...,FT_PCT,OREB,DREB,REB,AST,STL,BLK,TOV,PF,PLUS_MINUS
0,42022,1610612743,DEN,Denver Nuggets,0042200401,2023-06-01,DEN vs. MIA,W,239,104,...,0.800,6,39,45,29,4,4,10,8,11.0
1,42022,1610612748,MIA,Miami Heat,0042200401,2023-06-01,MIA @ DEN,L,241,93,...,1.000,11,32,43,26,5,4,8,15,-11.0
2,42022,1610612748,MIA,Miami Heat,0042200307,2023-05-29,MIA @ BOS,W,238,103,...,0.833,7,35,42,26,7,2,12,15,19.0
3,42022,1610612738,BOS,Boston Celtics,0042200307,2023-05-29,BOS vs. MIA,L,239,84,...,0.846,10,30,40,18,6,4,15,13,-19.0
4,42022,1610612748,MIA,Miami Heat,0042200306,2023-05-27,MIA vs. BOS,L,240,103,...,0.793,17,30,47,22,5,4,5,24,-1.0

In [16]:
games.columns

Index(['SEASON_ID', 'TEAM_ID', 'TEAM_ABBREVIATION', 'TEAM_NAME', 'GAME_ID',
       'GAME_DATE', 'MATCHUP', 'WL', 'MIN', 'PTS', 'FGM', 'FGA', 'FG_PCT',
       'FG3M', 'FG3A', 'FG3_PCT', 'FTM', 'FTA', 'FT_PCT', 'OREB', 'DREB',
       'REB', 'AST', 'STL', 'BLK', 'TOV', 'PF', 'PLUS_MINUS'],
      dtype='object')

In [17]:
games = games[['TEAM_NAME', 'GAME_ID','GAME_DATE', 'MATCHUP', 'WL','PLUS_MINUS']]

In [18]:
games

,TEAM_NAME,GAME_ID,GAME_DATE,MATCHUP,WL,PLUS_MINUS
0,Denver Nuggets,0042200401,2023-06-01,DEN vs. MIA,W,11.0
1,Miami Heat,0042200401,2023-06-01,MIA @ DEN,L,-11.0
2,Miami Heat,0042200307,2023-05-29,MIA @ BOS,W,19.0
3,Boston Celtics,0042200307,2023-05-29,BOS vs. MIA,L,-19.0
4,Miami Heat,0042200306,2023-05-27,MIA vs. BOS,L,-1.0
...,...,...,...,...,...,...
29995,Toronto Raptors,0021200081,2012-11-10,TOR vs. PHI,L,-10.0
29996,Minnesota Timberwolves,0021200084,2012-11-10,MIN @ CHI,L,-7.0
29997,Chicago Bulls,0021200084,2012-11-10,CHI vs. MIN,W,7.0
29998,Washington Wizards,0021200082,2012-11-10,WAS @ IND,L,-4.0
29999,Milwaukee Bucks,0021200086,2012-11-10,MIL vs. BOS,L,-4.0

In [20]:
games = games.sort_values('GAME_DATE')

In [21]:
games

                TEAM_NAME     GAME_ID   GAME_DATE      MATCHUP WL  PLUS_MINUS
29999     Milwaukee Bucks  0021200086  2012-11-10  MIL vs. BOS  L        -4.0
29982      Boston Celtics  0021200086  2012-11-10    BOS @ MIL  W         4.0
29983    Dallas Mavericks  0021200083  2012-11-10    DAL @ CHA  L        -4.0
29984  Philadelphia 76ers  0021200081  2012-11-10    PHI @ TOR  W        10.0
29985     Houston Rockets  0021200085  2012-11-10  HOU vs. DET  W        14.0
...                   ...         ...         ...          ... ..         ...
4              Miami Heat  0042200306  2023-05-27  MIA vs. BOS  L        -1.0
3          Boston Celtics  0042200307  2023-05-29  BOS vs. MIA  L       -19.0
2              Miami Heat  0042200307  2023-05-29    MIA @ BOS  W        19.0
1              Miami Heat  0042200401  2023-06-01    MIA @ DEN  L       -11.0
0          Denver Nuggets  0042200401  2023-06-01  DEN vs. MIA  W        11.0

[30000 rows x 6 columns]

In [23]:
games['avg_30_plus_minus']=games.groupby('TEAM_NAME')['PLUS_MINUS'].transform(lambda x: x.rolling(30, closed='left').mean())

In [25]:
games[games['TEAM_NAME']=='Miami Heat'].head(35)

,TEAM_NAME,GAME_ID,GAME_DATE,MATCHUP,WL,PLUS_MINUS,avg_30_plus_minus
29980,Miami Heat,0021200092,2012-11-11,MIA @ MEM,L,-18.0,NaN
29971,Miami Heat,0021200099,2012-11-12,MIA @ HOU,W,3.0,NaN
29941,Miami Heat,0021200117,2012-11-14,MIA @ LAC,L,-7.0,NaN
29923,Miami Heat,0021200121,2012-11-15,MIA @ DEN,W,5.0,NaN
29885,Miami Heat,0021200138,2012-11-17,MIA @ PHX,W,9.0,NaN
29821,Miami Heat,0021200163,2012-11-21,MIA vs. MIL,W,7.0,NaN
29788,Miami Heat,0021200186,2012-11-24,MIA vs. CLE,W,2.0,NaN
29716,Miami Heat,0021200220,2012-11-29,MIA vs. SAS,W,5.0,NaN
29686,Miami Heat,0021200233,2012-12-01,MIA vs. BKN,W,13.0,NaN
29647,Miami Heat,0021200252,2012-12-04,MIA @ WAS,L,-4.0,NaN
29622,Miami Heat,0021200268,2012-12-06,MIA vs. NYK,L,-20.0,NaN
29594,Miami Heat,0021200286,2012-12-08,MIA vs. NOH,W,16.0,NaN
29554,Miami Heat,0021200300,2012-12-10,MIA vs. ATL,W,9.0,NaN
29530,Miami Heat,0021200314,2012-12-12,MIA vs. GSW,L,-2.0,NaN
29478,Miami Heat,0021200339,2012-12-15,MIA vs. WAS,W,30.0,NaN
29434,Miami Heat,0021200359,2012-12-18,MIA vs. MIN,W,11.0,NaN
29402,Miami Heat,0021200378,2012-12-20,MIA @ DAL,W,15.0,NaN
29368,Miami Heat,0021200392,2012-12-22,MIA vs. UTA,W,16.0,NaN
29344,Miami Heat,0021200407,2012-12-25,MIA vs. OKC,W,6.0,NaN
29327,Miami Heat,0021200411,2012-12-26,MIA @ CHA,W,13.0,NaN
29295,Miami Heat,0021200428,2012-12-28,MIA @ DET,L,-10.0,NaN
29278,Miami Heat,0021200445,2012-12-29,MIA @ MIL,L,-19.0,NaN
29246,Miami Heat,0021200454,2012-12-31,MIA @ ORL,W,2.0,NaN
29214,Miami Heat,0021200469,2013-01-02,MIA vs. DAL,W,10.0,NaN
29195,Miami Heat,0021200481,2013-01-04,MIA vs. CHI,L,-7.0,NaN
29163,Miami Heat,0021200500,2013-01-06,MIA vs. WAS,W,28.0,NaN
29132,Miami Heat,0021200512,2013-01-08,MIA @ IND,L,-10.0,NaN
29106,Miami Heat,0021200529,2013-01-10,MIA @ POR,L,-2.0,NaN
29073,Miami Heat,0021200548,2013-01-12,MIA @ SAC,W,29.0,NaN
29034,Miami Heat,0021200561,2013-01-14,MIA @ UTA,L,-7.0,NaN
29003,Miami Heat,0021200579,2013-01-16,MIA @ GSW,W,17.0,4.100000
29000,Miami Heat,0021200583,2013-01-17,MIA @ LAL,W,9.0,5.266667
28921,Miami Heat,0021200619,2013-01-23,MIA vs. TOR,W,7.0,5.466667
28893,Miami Heat,0021200634,2013-01-25,MIA vs. DET,W,22.0,5.933333
28852,Miami Heat,0021200652,2013-01-27,MIA @ BOS,L,-2.0,6.500000

In [26]:
msk = games['MATCHUP'].str.contains('@')

In [28]:
games_away = games[msk]
games_home = games[~msk]

In [29]:
games_home

,TEAM_NAME,GAME_ID,GAME_DATE,MATCHUP,WL,PLUS_MINUS,avg_30_plus_minus
29999,Milwaukee Bucks,0021200086,2012-11-10,MIL vs. BOS,L,-4.0,NaN
29985,Houston Rockets,0021200085,2012-11-10,HOU vs. DET,W,14.0,NaN
29986,Charlotte Bobcats,0021200083,2012-11-10,CHA vs. DAL,W,4.0,NaN
29988,Golden State Warriors,0021200089,2012-11-10,GSW vs. DEN,L,-6.0,NaN
29992,Portland Trail Blazers,0021200088,2012-11-10,POR vs. SAS,L,-3.0,NaN
...,...,...,...,...,...,...,...
9,Miami Heat,0042200304,2023-05-23,MIA vs. BOS,L,-17.0,3.566667
6,Boston Celtics,0042200305,2023-05-25,BOS vs. MIA,W,13.0,7.866667
4,Miami Heat,0042200306,2023-05-27,MIA vs. BOS,L,-1.0,2.833333
3,Boston Celtics,0042200307,2023-05-29,BOS vs. MIA,L,-19.0,7.800000
0,Denver Nuggets,0042200401,2023-06-01,DEN vs. MIA,W,11.0,4.333333

In [30]:
games_away

,TEAM_NAME,GAME_ID,GAME_DATE,MATCHUP,WL,PLUS_MINUS,avg_30_plus_minus
29982,Boston Celtics,0021200086,2012-11-10,BOS @ MIL,W,4.0,NaN
29983,Dallas Mavericks,0021200083,2012-11-10,DAL @ CHA,L,-4.0,NaN
29984,Philadelphia 76ers,0021200081,2012-11-10,PHI @ TOR,W,10.0,NaN
29987,Detroit Pistons,0021200085,2012-11-10,DET @ HOU,L,-14.0,NaN
29989,Denver Nuggets,0021200089,2012-11-10,DEN @ GSW,W,6.0,NaN
...,...,...,...,...,...,...,...
8,Boston Celtics,0042200304,2023-05-23,BOS @ MIA,W,17.0,7.233333
7,Miami Heat,0042200305,2023-05-25,MIA @ BOS,L,-13.0,3.400000
5,Boston Celtics,0042200306,2023-05-27,BOS @ MIA,W,1.0,8.233333
2,Miami Heat,0042200307,2023-05-29,MIA @ BOS,W,19.0,2.166667
1,Miami Heat,0042200401,2023-06-01,MIA @ DEN,L,-11.0,3.266667

In [31]:
games_home.shape

(15000, 7)

In [32]:
games_away.shape

(15000, 7)

In [36]:
import pandas as pd
games_merged = pd.merge(games_home,games_away,on='GAME_ID',suffixes=('_home','_away'))

In [37]:
games_merged

,TEAM_NAME_home,GAME_ID,GAME_DATE_home,MATCHUP_home,WL_home,PLUS_MINUS_home,avg_30_plus_minus_home,TEAM_NAME_away,GAME_DATE_away,MATCHUP_away,WL_away,PLUS_MINUS_away,avg_30_plus_minus_away
0,Milwaukee Bucks,0021200086,2012-11-10,MIL vs. BOS,L,-4.0,NaN,Boston Celtics,2012-11-10,BOS @ MIL,W,4.0,NaN
1,Houston Rockets,0021200085,2012-11-10,HOU vs. DET,W,14.0,NaN,Detroit Pistons,2012-11-10,DET @ HOU,L,-14.0,NaN
2,Charlotte Bobcats,0021200083,2012-11-10,CHA vs. DAL,W,4.0,NaN,Dallas Mavericks,2012-11-10,DAL @ CHA,L,-4.0,NaN
3,Golden State Warriors,0021200089,2012-11-10,GSW vs. DEN,L,-6.0,NaN,Denver Nuggets,2012-11-10,DEN @ GSW,W,6.0,NaN
4,Portland Trail Blazers,0021200088,2012-11-10,POR vs. SAS,L,-3.0,NaN,San Antonio Spurs,2012-11-10,SAS @ POR,W,3.0,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...
14996,Miami Heat,0042200304,2023-05-23,MIA vs. BOS,L,-17.0,3.566667,Boston Celtics,2023-05-23,BOS @ MIA,W,17.0,7.233333
14997,Boston Celtics,0042200305,2023-05-25,BOS vs. MIA,W,13.0,7.866667,Miami Heat,2023-05-25,MIA @ BOS,L,-13.0,3.400000
14998,Miami Heat,0042200306,2023-05-27,MIA vs. BOS,L,-1.0,2.833333,Boston Celtics,2023-05-27,BOS @ MIA,W,1.0,8.233333
14999,Boston Celtics,0042200307,2023-05-29,BOS vs. MIA,L,-19.0,7.800000,Miami Heat,2023-05-29,MIA @ BOS,W,19.0,2.166667
15000,Denver Nuggets,0042200401,2023-06-01,DEN vs. MIA,W,11.0,4.333333,Miami Heat,2023-06-01,MIA @ DEN,L,-11.0,3.266667

In [38]:
games_merged['avg_30_plus_minus_diff']=games_merged['avg_30_plus_minus_home']-games_merged['avg_30_plus_minus_away']

In [39]:
games_merged

,TEAM_NAME_home,GAME_ID,GAME_DATE_home,MATCHUP_home,WL_home,PLUS_MINUS_home,avg_30_plus_minus_home,TEAM_NAME_away,GAME_DATE_away,MATCHUP_away,WL_away,PLUS_MINUS_away,avg_30_plus_minus_away,avg_30_plus_minus_diff
0,Milwaukee Bucks,0021200086,2012-11-10,MIL vs. BOS,L,-4.0,NaN,Boston Celtics,2012-11-10,BOS @ MIL,W,4.0,NaN,NaN
1,Houston Rockets,0021200085,2012-11-10,HOU vs. DET,W,14.0,NaN,Detroit Pistons,2012-11-10,DET @ HOU,L,-14.0,NaN,NaN
2,Charlotte Bobcats,0021200083,2012-11-10,CHA vs. DAL,W,4.0,NaN,Dallas Mavericks,2012-11-10,DAL @ CHA,L,-4.0,NaN,NaN
3,Golden State Warriors,0021200089,2012-11-10,GSW vs. DEN,L,-6.0,NaN,Denver Nuggets,2012-11-10,DEN @ GSW,W,6.0,NaN,NaN
4,Portland Trail Blazers,0021200088,2012-11-10,POR vs. SAS,L,-3.0,NaN,San Antonio Spurs,2012-11-10,SAS @ POR,W,3.0,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
14996,Miami Heat,0042200304,2023-05-23,MIA vs. BOS,L,-17.0,3.566667,Boston Celtics,2023-05-23,BOS @ MIA,W,17.0,7.233333,-3.666667
14997,Boston Celtics,0042200305,2023-05-25,BOS vs. MIA,W,13.0,7.866667,Miami Heat,2023-05-25,MIA @ BOS,L,-13.0,3.400000,4.466667
14998,Miami Heat,0042200306,2023-05-27,MIA vs. BOS,L,-1.0,2.833333,Boston Celtics,2023-05-27,BOS @ MIA,W,1.0,8.233333,-5.400000
14999,Boston Celtics,0042200307,2023-05-29,BOS vs. MIA,L,-19.0,7.800000,Miami Heat,2023-05-29,MIA @ BOS,W,19.0,2.166667,5.633333
15000,Denver Nuggets,0042200401,2023-06-01,DEN vs. MIA,W,11.0,4.333333,Miami Heat,2023-06-01,MIA @ DEN,L,-11.0,3.266667,1.066667

In [43]:
games_model = games_merged[['WL_home','avg_30_plus_minus_diff']].dropna()
games_model['WL_home'] = games_model['WL_home'].map({'W':1,'L':0})

In [44]:
games_model

       WL_home  avg_30_plus_minus_diff
433          0               -4.900000
449          1               -3.566667
450          0               -1.333333
451          1                5.433333
452          1                4.933333
...        ...                     ...
14996        0               -3.666667
14997        1                4.466667
14998        0               -5.400000
14999        0                5.633333
15000        1                1.066667

[14343 rows x 2 columns]

In [45]:
from sklearn.model_selection import train_test_split

In [47]:
df_train,df_test=train_test_split(games_model,stratify=games_model['WL_home'],test_size=0.2,random_state=7)

In [48]:
df_train.shape

(11474, 2)

In [49]:
df_test.shape

(2869, 2)

In [50]:
target = 'WL_home'
X_train = df_train.drop(columns = target)
y_train = df_train[target]

X_test = df_test.drop(columns = target)
y_test = df_test[target]

In [51]:
import xgboost as xgb

In [52]:
clf = xgb.XGBClassifier(random_state = 7)
clf.fit(X_train,y_train)

XGBClassifier(base_score=0.5, booster='gbtree', callbacks=None,
              colsample_bylevel=1, colsample_bynode=1, colsample_bytree=1,
              early_stopping_rounds=None, enable_categorical=False,
              eval_metric=None, feature_types=None, gamma=0, gpu_id=-1,
              grow_policy='depthwise', importance_type=None,
              interaction_constraints='', learning_rate=0.300000012,
              max_bin=256, max_cat_threshold=64, max_cat_to_onehot=4,
              max_delta_step=0, max_depth=6, max_leaves=0, min_child_weight=1,
              missing=nan, monotone_constraints='()', n_estimators=100,
              n_jobs=0, num_parallel_tree=1, predictor='auto', random_state=7, ...)

In [53]:
y_pred = clf.predict(X_test)

In [55]:
from sklearn.metrics import accuracy_score
accuracy_score(y_test,y_pred)

0.6343673753921227

In [56]:
#hyperparameter tuning
from sklearn.model_selection import RandomizedSearchCV

In [57]:
params = {'learning_rate': (0.0001,1),
         'n_estimators': [50,100,150,200,250],
         'max_depth': [2,3,4,5,6,7,8,9],
         'subsample': [0.7,0.8,0.9,1.0]}

In [58]:
Random_P = RandomizedSearchCV(estimator = clf, param_distributions = params, n_iter = 20, cv = 7, scoring = 'accuracy', random_state = 7)

In [59]:
Random_P.fit(X_train,y_train)

RandomizedSearchCV(cv=7,
                   estimator=XGBClassifier(base_score=0.5, booster='gbtree',
                                           callbacks=None, colsample_bylevel=1,
                                           colsample_bynode=1,
                                           colsample_bytree=1,
                                           early_stopping_rounds=None,
                                           enable_categorical=False,
                                           eval_metric=None, feature_types=None,
                                           gamma=0, gpu_id=-1,
                                           grow_policy='depthwise',
                                           importance_type=None,
                                           interaction_constraints='',
                                           learning_rate=0.300...
                                           max_delta_step=0, max_depth=6,
                                           max_leaves=0, min_child_weight=1,
                                           missing=nan,
                                           monotone_constraints='()',
                                           n_estimators=100, n_jobs=0,
                                           num_parallel_tree=1,
                                           predictor='auto', random_state=7, ...),
                   n_iter=20,
                   param_distributions={'learning_rate': (0.0001, 1),
                                        'max_depth': [2, 3, 4, 5, 6, 7, 8, 9],
                                        'n_estimators': [50, 100, 150, 200,
                                                         250],
                                        'subsample': [0.7, 0.8, 0.9, 1.0]},
                   random_state=7, scoring='accuracy')

In [60]:
Random_P.best_params_

{'subsample': 0.9,
 'n_estimators': 150,
 'max_depth': 3,
 'learning_rate': 0.0001}

In [61]:
Model_p = Random_P.best_estimator_
y_pred_p = Model_p.predict(X_test)

In [62]:
accuracy_score(y_test,y_pred_p)

0.6388985709306378

In [63]:
#EX1

team_home = 'Boston Celtics'
team_away = 'Toronto Raptors'


from joblib import dump, load
dump(Model_p, 'model_nba.joblib') 
model_saved = load('model_nba.joblib')

In [64]:
accuracy_score(y_test, model_saved.predict(X_test))

0.6388985709306378

In [66]:
def predict_games(team_home, team_away):
    gamefinder = leaguegamefinder.LeagueGameFinder(
        date_from_nullable='01/01/2021',
        league_id_nullable='00')
    games = gamefinder.get_data_frames()[0]
    games = games[
        ['TEAM_NAME', 'GAME_ID', 'GAME_DATE', 'MATCHUP', 'WL', 'PLUS_MINUS']]
    games['GAME_DATE'] = pd.to_datetime(games['GAME_DATE'])

    msk_home = (games['TEAM_NAME'] == team_home)
    games_30_home = games[msk_home].sort_values('GAME_DATE').tail(30)
    home_plus_minus = games_30_home['PLUS_MINUS'].mean()

    msk_away = (games['TEAM_NAME'] == team_away)
    games_30_away = games[msk_away].sort_values('GAME_DATE').tail(30)
    away_plus_minus = games_30_away['PLUS_MINUS'].mean()

    games_diff = home_plus_minus - away_plus_minus

    predict_home_win = model_saved.predict(np.array([games_diff]))[0]
    predict_winning_probability = model_saved.predict_proba(np.array([games_diff]))[0][1]
    return predict_home_win, predict_winning_probability

In [70]:
predict_games('Boston Celtics','Losangeles Lakers')

(0, 0.49637085)

In [71]:
import os
print(os.getcwd())

/Users/anudeepgoudrampur/Documents